# Generated by Django 5.0.14 on 2025-07-11 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expensegroup_expenses_group_groupexpensesplit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupexpensesplit',
            name='group_expense',
        ),
        migrations.RemoveField(
            model_name='groupexpensesplit',
            name='user',
        ),
        migrations.DeleteModel(
            name='ExpenseGroup',
        ),
        migrations.DeleteModel(
            name='GroupExpenseSplit',
        ),
    ]
